version: '3'
services:
  web:
    image: nginx:1.14
    ports: 
      - "3000:80"
    volumes:
      - gradle-report:/usr/share/nginx/html
  test:
    image: amadosaladino/selenium-gradle
    volumes:
      - ./test-project:/app
      - gradle-report:/report
      - gradle-repo:/root/.gradle/caches/modules-2/files-2.1
  gallery:
    image: ghcr.io/linuxserver/photoshow
    ports:
      - "8000:80"
    volumes:
      - ./test-project/screenshots:/Pictures:ro

volumes:
  gradle-repo:
  gradle-report: