version: '3'
services:
  web:
    build:
      context: ./web
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./web:/app
  test:
    build:
      context: ./test-project
    volumes:
      - ./test-project:/app
      - ./web/public:/app/output
  gallery:
    image: ghcr.io/linuxserver/photoshow
    ports:
      - "81:80"
    volumes:
      - ./test-project/screenshots:/Pictures:ro    